### ISSUE TITLE
Squiz.NamingConventions.ValidVariableName.NotCamelCaps issue on object keys

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-coding-standards#36]
If I have a object key that comes from the core or somewhere else the linter will throw an error.

![Screenshot 2020-10-07 at 07 51 26](https://user-images.githubusercontent.com/23283324/95292603-106ffa00-0872-11eb-90ed-8522f4fe4370.png)

for example:
````
$args = [
	'post_type' => ProductsPostType::SLUG,
	'post_per_page' => 50,
	'tax_query' => [ // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_tax_query
		[
				'taxonomy' => $item->object,
				'field'    => 'id',
				'terms'    => $item->object_id,
		],
	],
];
````

**Comment by dingo-d** [comment]
I've taken a look at the phpcs and the only way to fix this is to just do a `// phpcs:ignore` on the line where it happens 🤷🏼‍♂️ 

https://github.com/squizlabs/PHP_CodeSniffer/issues/2950
