### ISSUE TITLE
Same function requires different coding standards (Fully qualified)

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-coding-standards#53]
### Describe your bug

When using same function, in this case `get_main_site_id()` in PHP templates and PHP classes, different coding standard is required.

In PHP template it shouldn't be referenced with fully qualified name, and in PHP class it should be referenced with fully qualified name.

### Steps to Reproduce

Add function `get_main_site_id()` in PHP class and in PHP template.

### Expected behavior

It should be one coding standard for both cases.

### Environment info

- PHP version: 7.4
- ES coding standards: 1.1
- ES libs: dev-develop
- PHP code sniffer: ^0.6.2 || ^0.7

### Please confirm that you have searched existing issues in this repo.

Yes

**Comment by dingo-d** [comment]
Just remembered that this is not a bug. Template files live in a global namespace. As the error message from slevomat CS clearly states

> Function \get_main_site_id() should not be referenced via a fully qualified name, but via an unqualified name without the leading \, because the file does not have a namespace and the type cannot be put in a use statement.
