### ISSUE TITLE
Consider marking Components::renderPartial a safe method

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-coding-standards#56]
### Describe your feature request

Currently, doing `echo Components::renderPartial(...)` triggers a `Eightshift.Security.ComponentsEscape.OutputNotEscaped` sniff violation.

### Describe the solution you'd like

Ideally, we'd have the same approach here as with `Components::render`.

### Please confirm that you have searched existing issues and discussions about this feature.

Yes

**Comment by dingo-d** [comment]
For some reason, I was sure I added a public property where you could specify the safe methods for this sniff, but I guess I just thought about it as a feature.

I will add it, but it will have to wait for the WPCS 3.0.0 to come out (hopefully before the end of the year).

Then I'll do a bigger update and recheck if I can optimize the sniffs further.

**Comment by dingo-d** [comment]
This was added in the latest release, you can specify the list of allowed methods in the config:

```xml
<rule ref="Eightshift.Security.ComponentsEscape">
	<properties>
		<property name="allowedMethods" type="array">
			<element key="render" value="render"/>
			<element key="outputCssVariables" value="outputCssVariables"/>
			<element key="renderPartial" value="renderPartial"/>
		</property>
	</properties>
</rule>
```

@goranalkovic-infinum you can close this issue.
